repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Use the latest version of isort
    hooks:
      - id: isort
        args:
          - --profile=black  # Use Black-compatible sorting

  - repo: https://github.com/psf/black
    rev: 23.9.1  # Use the latest version of Black
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0  # Use the latest version of Flake8
    hooks:
      - id: flake8
        args:
          - --max-line-length=120
          - --format=default
          - --enable-extensions=DJ01  # Enable flake8-django rules
        additional_dependencies:
          - flake8-django  # Add flake8-django here

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1  # Use the latest version of MyPy
    hooks:
      - id: mypy
