# Generated by Django 3.2.20 on 2024-09-27 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingleTestElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Title')),
            ],
            options={
                'verbose_name': 'SingleTestElement',
                'verbose_name_plural': 'SingleTestElement',
                'ordering': ('title',),
            },
        ),
    ]
